### ISSUE TITLE
Can provide a `ion-content` demo ?

### ISSUE THREAD

**Issue by btpka3** [jvitor83/angular-pwa-seed#26]
Found this greet git repo when try to fix ionic + angular cli + url hashing + angular router.  Routing works ok, but found could not using `ion-content`. 

`ion-content` + `ion-nav` seems combined tightly, and some other ionic component ( such as FABs etc)

Had not tried `@angular/flex-layout` yet, do you had considerd to use`ion-content` , or any other layout components? 

---updated :
Found ionic team begin to do some investigations in milestone [@ionic/angular 4.0.0](https://github.com/ionic-team/ionic/milestone/65), such as:
- [Router](https://github.com/ionic-team/ionic/issues/13426)
- [Angular CLI?](https://github.com/ionic-team/ionic/issues/13425)

Hope these can be implemented in ionic 4.x.

**Comment by jvitor83** [comment]
@btpka3 sorry by the delay.
I don't get it! What do you mean by "use `ion-content`"?
If you see my https://github.com/jvitor83/angular-pwa-seed/blob/master/src/app/layout/menu/menu.component.html , i am using the `ion-content`.

About the tight coupling, you are right. "Some" Ionic components are tight coupled at NavController. Some of them you can fake some properties to make it work and use the events to get your expected behaviour, like i did with the `ion-tab` at https://github.com/jvitor83/angular-pwa-seed/blob/master/src/app/layout/layout-tab.component.ts#L20, by setting `[root]="dummyTab"`.

Anyway, i got no problem in using the `ion-content` or AngularRouter yet!

**Comment by btpka3** [comment]
Thanks for the link. (I should avoid trouble you by using github search first~) 

I got layout problems for responsive layout when using ionic `ion-content`、NavController related directives . I'll checkout that code.
